name: trafficVehicleCounter-cpu

dependencies:
  - python==3.8.5
  - pip
  - matplotlib
  - scipy
  - pip:
    - opencv-python
    - PySide2==5.15
    - pyqtgraph
    - qtmodern
    - lxml
    - tqdm
    - absl-py
    - easydict
    - pillow
    - h5py
